# Generated by Django 3.2.9 on 2021-11-14 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pekerti.functions.function


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gelombang',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Gelombang Id')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir')),
                ('link_kelas', models.CharField(blank=True, max_length=50, verbose_name='Link Kelas')),
                ('kode_akses_kelas', models.CharField(blank=True, max_length=50, verbose_name='Class Access Code')),
            ],
            options={
                'verbose_name_plural': 'Data Pelaksanaan Gelombang',
            },
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Peserta')),
                ('nidn', models.CharField(max_length=10, verbose_name='NIDN')),
                ('institusi_asal', models.CharField(max_length=50, verbose_name='Institusi Asal')),
                ('nomer_telp', models.CharField(max_length=16, verbose_name='Nomer Telepon')),
                ('link_transfer', models.FileField(upload_to=pekerti.functions.function.user_directory_path, validators=[pekerti.functions.function.validate_file_extension], verbose_name='Bukti Transfer')),
                ('link_penugasan', models.FileField(upload_to=pekerti.functions.function.user_directory_path, validators=[pekerti.functions.function.validate_file_extension], verbose_name='Dokumen Penugasan')),
                ('link_kesanggupan', models.FileField(upload_to=pekerti.functions.function.user_directory_path, validators=[pekerti.functions.function.validate_file_extension], verbose_name='Dokumen Kesanggupan')),
                ('link_sertifikat', models.CharField(blank=True, max_length=254, verbose_name='Sertifikat')),
                ('is_validated', models.BooleanField(verbose_name='Status Validasi')),
                ('gelombang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pekerti.gelombang', verbose_name='Gelombang')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Peserta',
            },
        ),
    ]
