# Generated by Django 3.2.9 on 2021-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekerti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelombang',
            name='jumlah_jam',
            field=models.IntegerField(default=1, verbose_name='Jumlah Jam Pelaksanaan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peserta',
            name='is_validated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status Validasi'),
        ),
    ]
