# Generated by Django 3.2.9 on 2021-11-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='avatar',
        ),
    ]
