# Generated by Django 3.2.9 on 2021-11-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_user', '0003_remove_user_is_pekerti_peserta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pekerti_peserta',
            field=models.BooleanField(default=False, verbose_name='Apakah Peserta Pekerti'),
        ),
    ]
